#!/bin/sh
#description: backup mozilla configurations
#usage: backup-mozilla [options] [dir]

#example: backup-mozilla
#tar: Removing leading `/' from member names
#/home/user/.mozilla/
#/home/user/.mozilla/firefox/
#...

progname="$(expr "${0}" : '.*/\([^/]*\)')"

_usage() {
    printf "%s\\n" "Usage: ${progname} [options] [dir]"
    printf "%s\\n" "Backup Mozilla configurations."
    printf "\\n"
    printf "%s\\n" "  -n           number of copies to save"
    printf "%s\\n" "  -c           continue with backup even if firefox isn't running"
    printf "%s\\n" "  -s           skip backup even if firefox is running"
    printf "%s\\n" "  -h, --help   show this help message and exit"
    printf "\\n"
    printf "%s\\n" "  dir          directory to save backups (~/.mozilla-backups by default)"
}

_die() {
    [ -z "${1}" ] || printf "%s\\n" "${*}" >&2
    _usage >&2; exit 1
}

_is_int() {
    #look for an integer, returns 0 on success, 1 otherwise
    #http://www.unix.com/shell-programming-and-scripting/172070-help-scripting-command.html
    case "${1}" in
        *[!0-9]*|"") return 1 ;;
    esac
}

_basename() {
    #alternative basename portable version, faster! but with possible drawbacks
    [ -z "${1}" ] && return 1 || _basename__name="${1}"
    [ -z "${2}" ] || _basename__suffix="${2}"
    case "${_basename__name}" in
        /*|*/*) _basename__name="${_basename__name##*/}"
    esac

    if [ -n "${_basename__suffix}" ] && [ "${#_basename__name}" -gt "${#2}" ]; then
        _basename__name="${_basename__name%$_basename__suffix}"
    fi

    printf "%s" "${_basename__name}"
}

_bmozilla() {
    [ -z "${1}" ] && return 1
    mkdir -p "${1}" >/dev/null 2>&1
    if [ -d "${HOME}"/.mozilla ]; then
        if command -v "lrzip" >/dev/null 2>&1; then
            tar cf - "${HOME}"/.mozilla | nice lrzip -N 19 -q -L 9 > "${1}"/mozilla-"$(date +%Y-%m-%d:%H:%M)".tar.lrz
        elif command -v "lzma" >/dev/null 2>&1; then
            tar cf - "${HOME}"/.mozilla | nice lzma -9 > "${1}"/mozilla-"$(date +%Y-%m-%d:%H:%M)".tar.lzma
        elif command -v "bzip2" >/dev/null 2>&1; then
            tar cf - "${HOME}"/.mozilla | nice bzip2 > "${1}"/mozilla-"$(date +%Y-%m-%d:%H:%M)".tar.bz2
        else
            tar cf - "${HOME}"/.mozilla | nice gzip  > "${1}"/mozilla-"$(date +%Y-%m-%d:%H:%M)".tar.gz
        fi
    else
        return 1
    fi
}

_blimiter() {
    [ -z "${1}" ] && return 1
    [ -z "${2}" ] && return 1

    _blimiter__backups="$(find "${1}" -maxdepth 1 -type f | wc -l)"
    _blimiter__rm="$(($_blimiter__backups - $2))"

    if [ "${_blimiter__backups}" -gt "${2}" ]; then
        rm -rf $(find "${1}" -type f -printf '%T+ %p\n' | sort | head -"${_blimiter__rm}" | awk '{print $2}')
    fi
}

_meta_backup_mozilla() {
    for arg; do args="${args} ${arg}"; done
    _meta_backup_mozilla__users="$(getent passwd | awk -F: '{if ($3 >= 1000 && $3 < 60000) print $1}')"
    for _meta_backup_mozilla__user in ${_meta_backup_mozilla__users}; do
        su "${_meta_backup_mozilla__user}" -c "backup-mozilla ${args}"
    done
    exit "${$?}"
}

if [ ! -t 0 ]; then
    #there is input comming from pipe or file, add to the end of $@
    set -- "${@}" $(cat)
fi

[ X"${LOGNAME}" = X"root" ] && _meta_backup_mozilla "${@}"

for arg; do #parse options
    case "${arg}" in
        --) shift; break          ;;
        -h|--help) _usage && exit ;;
        -c) cont="true"; shift    ;;
        -s) skip="true"; shift    ;;
        -n) if [ "${#}" -gt "1" ]; then
                blimit="$(printf "%s " "${@}" | awk '{print $2}')"
                shift 2
                if ! _is_int "${blimit}"; then
                    _die "Option '${arg}' requires a number: '${blimit}'"
                fi
            else
                _die "Option '${arg}' requires a parameter"
            fi ;;
        -*) _die "${progname}: unrecognized option '${arg}'" ;;
    esac
done

[ -z "${1}" ] && dir="${HOME}"/.mozilla-backups || dir="${1}"

if [ ! -z "${cont}" ]; then
    _bmozilla "${dir}"
elif [ ! -z "${skip}" ]; then
    :
else
    if pgrep firefox >/dev/null 2>&1; then
        _bmozilla "${dir}"
    elif [ ! -z "${blimit}" ]; then
        :
    else
        exit 1
    fi
fi

[ -z "${blimit}" ] && blimit="5"
_blimiter "${dir}" "${blimit}"
