#!/bin/sh
#description: dmenu for mpd
#usage: dmenu-mpd is best suited for launching from a shortcut

#example: dmenu-mpd
#a gui menu appears asking for which song to play

#looks better with a xft powered dmenu:
#https://bugs.launchpad.net/ubuntu/+source/suckless-tools/+bug/1093745
DMENU='dmenu -p > -i -fn Bahamas-10 -nb #000000 -nf #ffffff -sb #000000 -sf #cfd000'

_die() {
    [ -z "${1}" ] && _die_msg="dmenu" || _die_msg="${1}"
    printf "%b%b\\n" "${_die_msg}" ", press <Enter> to exit" | ${DMENU}
    exit 1
}

if ! command -v "dmenu" >/dev/null 2>&1; then
    printf "%s\\n" "install 'dmenu' to run this program" >&2
    exit 1
elif ! command -v "mpc" >/dev/null 2>&1; then
    _die "install 'mpd' to run this program"
fi

song="$(mpc playlist | ${DMENU})" || exit 1
song="$(mpc playlist | awk '{if($0 == "'"${song}"'") {print NR}}')"
[ -z "${song}" ] && exit 1 || mpc play "${song}"
