#!/bin/sh
#description: dmenu for mpd
#usage: dmenu-mpd is best suited for launching from a shortcut

#example: dmenu-mpd
#a gui menu appears asking for which song to play

progname="$(expr "${0}" : '.*/\([^/]*\)')"

#variables are impractical to save complex cmds because of shell expantion
#therefore functions are required: http://mywiki.wooledge.org/BashFAQ/050
DMENU() { dmenu -p 'Mpd' -i -fn Bahamas-10 \
                -nb \#000000 -nf \#ffffff -sb \#cfd000 -sf \#000000; }
#looks better on xft powered dmenu:
#https://bugs.launchpad.net/ubuntu/+source/suckless-tools/+bug/1093745

_usage() {
    printf "%s\\n" "Usage: ${progname} [song]"
    printf "%s\\n" "Dmenu for mpd."
    printf "%s\\n"
    printf "%s\\n" "  -h, --help      show this message and exit"
}

_die() {
    [ -n "${1}" ] && _die_msg="${1}" || exit 1
    printf "%b%b\\n" "${_die_msg}" ", press <Enter> to exit" | DMENU
    exit 1
}

_notify() {
    [ -z "${1}" ] && return 1
    kill -9 $(pgrep notify-osd) >/dev/null 2>&1
    if ! DISPLAY=${DISPLAY:-:0} notify-send -t 1000 "${1}" "${2}"; then
        if command -v "gxmessage" 2>/dev/null; then
            font="Monaco 9"
            DISPLAY=${DISPLAY:-:0} gxmessage "${font:+-fn "$font"}" "${1}" "ok"
        elif command -v "xmessage" 2>/dev/null; then
            font="fixed"
            DISPLAY=${DISPLAY:-:0}  xmessage "${font:+-fn "$font"}" "${1}" "ok"
        fi
    fi
}

if [ ! -t 0 ]; then
    #add input comming from pipe or file to $@
    set -- "${@}" $(cat)
fi

for arg in "${@}"; do #parse options
    case "${arg}" in
        -h|--help) _usage && exit ;;
    esac
done

if [ -z "${1}" ]; then
    if ! command -v "dmenu" >/dev/null 2>&1; then
        printf "%s\\n" "install 'dmenu' to run this program" >&2
        exit 1
    elif ! command -v "mpc" >/dev/null 2>&1; then
        _die "install 'mpc' to run this program"
    fi
    song="$(mpc playlist | DMENU)"
else
    song="$(mpc playlist | grep -i "${@}" 2>/dev/null | head -1 )"
fi

if [ -z "${song}" ]; then
    _die
else
    song="$(mpc playlist | awk '{if($0 == "'"${song}"'") {print NR}}')" || exit 1
    error_msg="$(mpc play "${song}" 2>&1 1>/dev/null)"
    if [ X"${?}" != X"0" ]; then
        _notify "Error" "${error_msg}"
        exit 1
    fi
fi
