#!/bin/sh
#description: dmenu based vbox menu
#usage: dmenu-vbox is best suited for launching from a shortcut

#example: dmenu-vbox
#appears a gui menu appears asking for which virtual machine to boot

#looks better with a xft powered dmenu:
#https://bugs.launchpad.net/ubuntu/+source/suckless-tools/+bug/1093745
DMENU='dmenu -p > -i -fn Bahamas-10 -nb #000000 -nf #ffffff -sb #000000 -sf #3B5998'

_die() {
    [ -z "${1}" ] && _die_msg="dmenu" || _die_msg="${1}"
    printf "%b%b\\n" "${_die_msg}" ", press <Enter> to exit" | ${DMENU}
    exit 1
}

if ! command -v "dmenu" >/dev/null 2>&1; then
    printf "%s\\n" "install 'dmenu' to run this program" >&2
    exit 1
elif ! command -v "vboxmanage" >/dev/null 2>&1; then
    _die "install 'virtualbox' to run this program"
fi

vboxmachine="$(vboxmanage list vms | cut -d\" -f2 | ${DMENU})"

[ -z "${vboxmachine}" ] && exit 1 || vboxmanage -q startvm "${vboxmachine}" --type gui
