#!/bin/sh
#description: dmenu txt2speech app
#usage: dmenu-txt2speech is best suited for launching from a shortcut

#example: dmenu-txt2speech
#a gui menu appears asking for which phrase to say, default to english voice

#looks better with a xft powered dmenu:
#https://bugs.launchpad.net/ubuntu/+source/suckless-tools/+bug/1093745
DMENU='dmenu -p > -i -fn Bahamas-10 -nb #000000 -nf #ffffff -sb #000000 -sf #aaffaf'

_usage()
{
    printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') [string] ..." >&2
    printf "%s\\n" "Dmenu txt2speech." >&2
    printf "%s\\n" >&2
    printf "%s\\n" "  -h, --help   show this help message and exit" >&2
    exit 1
}

_die()
{
    [ -z "${1}" ] && _die_msg="dmenu" || _die_msg="${1}"
    printf "%b%b\\n" "${_die_msg}" ", press <Enter> to exit" | ${DMENU}
    exit 1
}

if [ ! -t 0 ]; then
    #there is input comming from pipe or file, add to the end of $@
    set -- "${@}" $(cat)
fi

for arg; do #parse options
    case "${arg}" in
        -h|--help) _usage ;;
    esac
done

if [ -z "${1}" ]; then
    if ! command -v "dmenu" >/dev/null 2>&1; then
        printf "%s\\n" "you need to install 'dmenu' to run this program" >&2
        exit 1
    elif ! command -v "txt2speech" >/dev/null 2>&1; then
        _die "you need to install 'txt2speech' to run this program"
    fi
    phrase="$(${DMENU} <&- && printf "\\n")"
else
    phrase="${@}"
fi

[ -z "${phrase}" ] && exit 1;

if [ -f "$(command -v "xclip")" ]; then
    clipboard="xclip -o"
elif [ -f "$(command -v "sselp")" ]; then
    clipboard="sselp"
else
    clipboard="echo clipboard not available"
fi

if [ X"$(printf "%s" "${phrase}" | cut -d' ' -f2)" = X"-" ]; then
    phrase="$(printf "%s" "${phrase}" | cut -d' ' -f1) $(${clipboard})"
fi

txt2speech ${phrase}
