#!/bin/sh
#description: pretty i3 bar, requires conky
#usage: use only as argument in status_command (~/.i3/config)

 #minos statusbar looks better with the xbc icon patch

_usage()
{
    printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') [options]"
    printf "%s\\n" "WARNING, Only use this program as an argument to status_command in i3 (~/.i3/config)"
    printf "\\n"
    printf "%s\\n" "  -h, --help   show this help message and exit"
}

_die()
{
    [ -z "${1}" ] && return 1
    printf "%s\\n" "${*}" >&2
    _usage >&2; exit 1
}

exec 0>/dev/null #i3bar click events (58e68) make impossible to read stdin without crashing it
#if [ ! -t 0 ]; then
    ##there is input comming from pipe or file, add to the end of $@
    #set -- "${@}" $(cat)
#fi

for arg; do #parse options
    case "${arg}" in
        --) shift; break  ;;
        -h|--help) _usage && exit ;;
        -*) _die "$(expr "${0}" : '.*/\([^/]*\)'): unrecognized option '${arg}'" ;;
    esac
done

progname="$(minos-config m-statusbar 2>/dev/null)"
if [ ! -z "${progname}" ]; then
    case "${progname}" in
        minos-statusbar) : ;;
        *) #exec sh -c "${progname}"
           exec "${progname}" ;;
    esac
fi

[ X"$(minos-config statusbar 2>/dev/null)" = X"no" ] && return 0

minos_statusbar="$(minos-config m-statusbar-config 2>/dev/null)"
if [ -z "${minos_statusbar}" ]; then
    if [ -f "${HOME}"/.minos/statusbar ]; then
        minos_statusbar="${HOME}/.minos/statusbar"
    elif [ -f /etc/minos/statusbar ]; then
        minos_statusbar="/etc/minos/statusbar"
    fi
fi

if [ -z "${minos_statusbar}" ]; then
    printf "%s\\n" "minos-statusbar: couldn't find config file, exiting." >&2
    return 1
else
    minos_statusbar_icons="$(minos-config m-statusbar-icons 2>/dev/null)"
    [ -z "${minos_statusbar_icons}" ] && minos_statusbar_icons="sm4tik"
    sed "s:sm4tik:${minos_statusbar_icons}:g" ${minos_statusbar} > /tmp/minos-statusbar

    #http://www.reddit.com/r/unixporn/comments/22jgrh/debiani3_minimalist_crisp_clear/
    echo "{\"version\":1}"
    echo '['
    echo '[] ,'
    conky -c /tmp/minos-statusbar
    #if command -v "setsid" >/dev/null 2>&1; then
        #(setsid conky -c /tmp/minos-statusbar &)
    #else
        #exec conky -c /tmp/minos-statusbar
    #fi
fi
