#!/bin/sh
#description: run initial apps in minos
#usage: minos-autostart

progname="$(expr "${0}" : '.*/\([^/]*\)')"

_usage() {
    printf "%s\\n" "Usage: ${progname} [options]"
    printf "%s\\n" "Run startup apps in minos."
    printf "\\n"
    printf "%s\\n" "  -h, --help   show this help message and exit"
}

_die() {
    [ -z "${1}" ] || printf "%s\\n" "${*}" >&2
    _usage >&2; exit 1
}

if [ ! -t 0 ]; then
    #there is input comming from pipe or file, add to the end of $@
    set -- "${@}" $(cat)
fi

for arg; do #parse options
    case "${arg}" in
        --) shift; break ;;
        -h|--help) _usage && exit ;;
        -*) _die "${progname}: unrecognized option '${arg}'" ;;
    esac
done

[ X"$(minos-config autostart 2>/dev/null)" = X"no" ]  && return 0
if [ -z "$(minos-config autostart-config 2>/dev/null)" ]; then
    [ -e /etc/minos/autostart ]       && exec /etc/minos/autostart
    [ -e "${HOME}"/.minos/autostart ] && exec "${HOME}"/.minos/autostart
else
   exec $(minos-config autostart-config 2>/dev/null)
fi
