#!/bin/sh
#description: show shortcut information in minos
#usage: minos-help

_usage()
{
    printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') [options]"
    printf "%s\\n" "Minos help window."
    printf "\\n"
    printf "%s\\n" "  -h, --help   show this help message and exit"
}

_die()
{
    [ -z "${1}" ] || printf "%s\\n" "${*}" >&2
    _usage >&2; exit 1
}

_whereis()
{
    [ -z "${1}" ] && return 1
    if ! command -v "${1}" 2>/dev/null; then
        return 1
    fi
}

if [ ! -t 0 ]; then
    #there is input comming from pipe or file, add to the end of $@
    set -- "${@}" $(cat)
fi

for arg; do #parse options
    case "${arg}" in
        --) shift; break  ;;
        -h|--help) _usage && exit ;;
        -*) _die "$(expr "${0}" : '.*/\([^/]*\)'): unrecognized option '${arg}'" ;;
    esac
done

running="$(ps aux | awk '/got it/ {if ($0 !~ "awk") print $2}')"
[ -n "${running}" ] && exit 1

XMESSAGE="$(_whereis gxmessage)" && geometry="-geometry 400x520" || XMESSAGE="xmessage"
font="Monaco 9"

[ X"${XMESSAGE}" = X"xmessage" ] && font="fixed"

if [ -f "${HOME}"/.minos/help ]; then
    help="${HOME}"/.minos/help
elif [ -f /etc/minos/help ]; then
    help="${HOME}"/.minos/help
else
    printf "%s\\n" 'No help available' > /tmp/minos-help
    help=/tmp/minos-help
fi

${XMESSAGE} ${geometry} ${font:+-fn "$font"} -file "${help}" -buttons "got it"
