#!/bin/sh
#description: control player apps, currently mpd,mplayer,mpv
#usage: player-ctrl [play|pause|toggle|next|previous]

#example: player-ctrl next
#play next song in queue

_usage()
{
    printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') play|pause|toggle|next|previous" >&2
    printf "%s\\n" "Control player apps." >&2
    exit 1
}

_die()
{
    [ -z "${1}" ] && return 1
    printf "%b\\n" "$(expr "${0}" : '.*/\([^/]*\)'): ${*}" >&2
    exit 1
}

_mplayer()
{
    [ -z "${1}" ] && return 1
    _mplayer__fifo="$(cat etc/mplayer/mplayer.conf ~/.mplayer/config 2>/dev/null | \
        awk '/^input=file=/ {sub(/^input=file=/, ""); print}' | tail -1)"

    [ -n "${_mplayer__fifo}" ] && [ ! -e "${_mplayer__fifo}" ] && mkfifo "${_mplayer__fifo}"

    [ ! -p "${_mplayer__fifo}" ] && return 1
    case "${1}" in
        play|pause|toggle) printf "%s\\n" "pause"      > "${_mplayer__fifo}" ;;
        next)              printf "%s\\n" "pt_step 1"  > "${_mplayer__fifo}" ;;
        previous)          printf "%s\\n" "pt_step -1" > "${_mplayer__fifo}" ;;
    esac
}

_mpd()
{
    [ -z "${1}" ] && return 1
    case "${1}" in
        play)     mpc play >/dev/null ;;
        pause)    [ "$(mpc status | grep playing)" ] && mpc pause 1>/dev/null ;;
        toggle)   [ "$(mpc status | grep playing)" ] && mpc pause 1>/dev/null || mpc play 1>/dev/null ;;
        next)     mpc next > /dev/null ;;
        previous) mpc prev > /dev/null ;;
    esac
}

_player_ctrl()
{
    [ -z "${1}" ] && return 1
    if [ -n "$(pgrep mplayer)" ] || [ -n "$(pgrep mpv)" ]; then
        if [ "$(mpc status | grep playing)" ]; then
            mpc pause 1>/dev/null
        else
            _mplayer "${1}"
        fi
        return "${?}"
    fi
    [ -n "$(pgrep mpd)" ] && _mpd "${1}" || :
}

if [ ! -t 0 ]; then
    #there is input comming from pipe or file, add to the end of $@
    set -- "${@}" $(cat)
fi

[ X"${#}" != X"1" ] && _usage

case "${1}" in
         pl*) _param="play"     ;;
    pa*|stop) _param="pause"    ;;
         pr*) _param="previous" ;;
          n*) _param="next"     ;;
          t*) _param="toggle"   ;;
           *) _usage            ;;
esac

_player_ctrl "${_param}"
