#!/bin/sh
#description: control player apps
#usage: player-ctrl [play|pause|toggle|next|previous]

#example: player-ctrl next
#play next song in queue

_usage() {
    printf "%s\\n" "Usage: ${progname} play|pause|status|print [PARAM]|toggle|next|previous"
    printf "%s\\n" "Control player apps."
}

_die() {
    [ -z "${1}" ] || printf "%s\\n" "${*}" >&2
    _usage >&2; exit 1
}

_str2lower() {
    [ -z "${1}" ] && return 1
    printf "%s\\n" "${@}" | \
    tr 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' 'abcdefghijklmnopqrstuvwxyz'
}

_dbus_send() {
    if [ "$(id -u)" = 0 ]; then #root
        if [ -z "${_dbus__address}" ]; then
            _dbus__pid="$(pgrep dbus-launch|head -1)"
            _dbus__user="$(grep -z USER /proc/"${_dbus__pid}"/environ | sed 's/USER=//')"
            _dbus__address="$(awk \
                '/^DBUS_SESSION_BUS_ADDRESS/{sub(/DBUS_SESSION_BUS_ADDRESS=/,"");print $0;exit}' \
                /home/"${_dbus__user}"/.dbus/session-bus/$(dbus-uuidgen --get)-*)"
        fi
        #I've no idea what I'm doing
        su "${_dbus__user}" -c "dbus-send $*"
        #su "${_dbus__user}" -c "sh -c 'DBUS_SESSION_BUS_ADDRESS=\"${_dbus__address}\" dbus-send $*'"
    else
        dbus-send ${@}
    fi
}

_mplayer() {
    [ -z "${1}" ] && return 1
    _mplayer__fifo="$(cat etc/mplayer/mplayer.conf ~/.mplayer/config 2>/dev/null | \
        awk '/^input=file=/ {sub(/^input=file=/, ""); print}' | tail -1)"

    [ -n "${_mplayer__fifo}" ] && [ ! -e "${_mplayer__fifo}" ] && mkfifo "${_mplayer__fifo}"

    [ ! -p "${_mplayer__fifo}" ] && return 1
    case "${1}" in
        play|toggle) printf "%s\\n" "pause"         > "${_mplayer__fifo}" ;;
        pause)       printf "%s\\n" "pausing pause" > "${_mplayer__fifo}" ;;
        status|print) : ;;
        next)        printf "%s\\n" "pt_step 1"     > "${_mplayer__fifo}" ;;
        previous)    printf "%s\\n" "pt_step -1"    > "${_mplayer__fifo}" ;;
        print)       case "${2}" in
                        ''|title) : ;;
                     esac
                     ;;
    esac
}

_mpd() {
    [ -z "${1}" ] && return 1
    case "${1}" in
        play)     mpc play   ;;
        pause)    mpc pause  ;;
        status)   mpc status ;;
        toggle)   [ "$(mpc status 2>&1 | grep playing)" ] && mpc pause || mpc play ;;
        next)     mpc next   ;;
        previous) mpc prev   ;;
        print)
            case "${2}" in
                ''|title) mpc status |awk 'NR == 1 {gsub(/"/,""); gsub(/\\/,"/"); print}' ;;
            esac
            ;;
    esac
}

_spotify_remote() {
    #also called connect: https://www.spotify.com/mx/connect/
    [ -z "${1}" ] && return 1

    #read spotify tokens
    [ -f ~/.spotify ] && . ~/.spotify || return 1
    app_client_id="${app_client_id:-43e8830355074eb8b73bba56d95b8b81}"
    app_private_id="${app_private_id:-06e8c6c3d0284e0ca5dfc7e5dd1da15e}"
    user_refresh_token="${refresh_token}"

    [ -z "${user_refresh_token}" ] && return 1

    if [ -z "${_spotify_remote__token}" ]; then
        _spotify_remote__token="$(curl -s https://accounts.spotify.com/api/token \
            -H "Authorization: Basic $(printf "${app_client_id}:${app_private_id}" | base64 | tr -d '\n')" \
            -d grant_type=refresh_token -d refresh_token="${user_refresh_token}" | \
            awk -F \" '/access_token/ {gsub(",",""); print $4; exit}'
        )"
    fi

    if [ -z "${_spotify_remote__device}" ]; then
        _spotify_remote__device="$(
            curl -s "https://api.spotify.com/v1/me/player/devices" \
                -H "Accept: application/json" \
                -H "Content-Type: application/json" \
                -H "Authorization: Bearer ${_spotify_remote__token}" | \
            awk '/id/ {gsub("\"","");gsub(",",""); print $NF; exit}'
        )"
    fi

    [ -z "${_spotify_remote__device}" ] && return 1

    _spotify__endpoint() {
        [ -z "${1}" ] && return 1

        curl -s -X "${1}"                       \
            -d ""                               \
            -H "Accept: application/json"       \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${_spotify_remote__token}" \
            "https://api.spotify.com/v1/me/player${2}"
    }

    case "${1}" in
        #https://developer.spotify.com/console/player/
        play|pause) _spotify__endpoint "PUT" "/${1}?device_id=${_spotify_remote__device}" ;;
        status)     _spotify__endpoint "GET"  ;;
        toggle)
            if _spotify_remote status | grep "is_playing" | grep "true"; then
               _spotify_remote pause
            else
               _spotify_remote play
            fi
            ;;
        next|previous) _spotify__endpoint "POST" "/${1}?device_id=${_spotify_remote__device}" ;;
        print)
            case "${2}" in
                ''|title) mpc status|awk 'NR == 1 {gsub(/"/,""); gsub(/\\/,"/"); print}' ;;
            esac
            ;;
    esac
}

_dbus_player() {
    [ -z "${1}" ] && return 1
    _dbus__dest="${2}"
    _dbus__mpris="${3}"
    _dbus__mpris_ctrl="${4}"

    _dbus_print_current_song() {
        sleep 0.2 || sleep 1
        _dbus__output="$(_dbus_send --print-reply             \
                                    --dest="${_dbus__dest}"   \
        "${_dbus__mpris}" org.freedesktop.DBus.Properties.Get \
        string:"${_dbus__mpris_ctrl}" string:Metadata)" || return "${?}"
        printf "%s\\n" "${_dbus__output}" | \
            awk -v status="${1}" 'BEGIN {RS=" entry\\("; FS="\""};
            /artist/ {artist = $4}; /title/ {title = $4} END {
            if (length(status) == 0) {if(length(artist) == 0)
                {print title} else {print artist" - "title}}
            else {print artist" - "title, status}}'
    }

    case "${1}" in
        play)     _dbus_send --print-reply \
                             --dest="${_dbus__dest}" \
                             "${_dbus__mpris}" "${_dbus__mpris_ctrl}.Play" \
                             >/dev/null && _dbus_print_current_song
                  ;;
        pause)    _dbus_send --print-reply \
                             --dest="${_dbus__dest}" \
                             "${_dbus__mpris}" "${_dbus__mpris_ctrl}.Pause" \
                             >/dev/null && _dbus_print_current_song "[PAUSED]"
                  ;;
        status)    _dbus_print_current_song ;;
        toggle)   _dbus_send --print-reply \
                             --dest="${_dbus__dest}" \
                             "${_dbus__mpris}" "${_dbus__mpris_ctrl}.PlayPause" \
                             >/dev/null && _dbus_print_current_song
                  ;;
        next)     _dbus_send --print-reply \
                             --dest="${_dbus__dest}" \
                             "${_dbus__mpris}" "${_dbus__mpris_ctrl}.Next" \
                             >/dev/null && _dbus_print_current_song
                  ;;
        previous) _dbus_send --print-reply \
                             --dest="${_dbus__dest}" \
                             "${_dbus__mpris}" "${_dbus__mpris_ctrl}.Previous" \
                             >/dev/null && _dbus_print_current_song
                  ;;
        print)    _dbus_print_current_song ;;
    esac
}

_spotify() {
    [ -z "${1}" ] && return 1
    _dbus__dest="org.mpris.MediaPlayer2.spotify"
    _dbus__mpris="/org/mpris/MediaPlayer2"
    _dbus__mpris_ctrl="$(printf "%s\\n" "${_dbus__mpris}"|sed -e 's:/::' -e 's:/:.:g').Player"

    _dbus_player "${1}" "${_dbus__dest}" "${_dbus__mpris}" "${_dbus__mpris_ctrl}"
}

_music_is_playing_in_chrome() {
    dbus-send --session --dest=org.freedesktop.DBus --type=method_call \
              --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames | \
        grep MediaPlayer2.chrome >/dev/null && return 1 || return 0
}

_chrome() {
    [ -z "${1}" ] && return 1
    _dbus__dest="$(dbus-send --session --dest=org.freedesktop.DBus \
                             --type=method_call                    \
                             --print-reply /org/freedesktop/DBus   \
                             org.freedesktop.DBus.ListNames |      \
                       awk -F\" '/chrome/{print $2}')"
    _dbus__mpris="/org/mpris/MediaPlayer2"
    _dbus__mpris_ctrl="$(printf "%s\\n" "${_dbus__mpris}"|sed -e 's:/::' -e 's:/:.:g').Player"

    _dbus_player "${1}" "${_dbus__dest}" "${_dbus__mpris}" "${_dbus__mpris_ctrl}"
}

_player_ctrl() {
    #preference
    #1.- local/remote spotify
    #2.- chrome
    #3.- mplayer|mpd
    #4.- mpd
    [ -z "${1}" ] && return 1

    if [ -n "$(pgrep spotify)" ] || _spotify_remote status >/dev/null 2>&1; then
        [ X"${1}" = X"print" ] && _spotify "${@}" && return "${?}"
        if [ "$(mpc status 2>&1 | grep playing)" ]; then
            _mpd pause
        elif [ -n "$(pgrep mplayer)" ] || [ -n "$(pgrep mpv)" ]; then
            _mplayer pause
        else
            _spotify "${@}" || _spotify_remote "${@}"
        fi
    elif _music_is_playing_in_chrome; then
        [ X"${1}" = X"print" ] && _chrome "${@}" && return "${?}"
        if [ "$(mpc status 2>&1 | grep playing)" ]; then
            _mpd pause
        elif [ -n "$(pgrep mplayer)" ] || [ -n "$(pgrep mpv)" ]; then
            _mplayer pause
        else
            _chrome "${@}"
        fi
    elif [ -n "$(pgrep mplayer)" ] || [ -n "$(pgrep mpv)" ]; then
        [ X"${1}" = X"print" ] && _mplayer "${@}" && return "${?}"
        if [ "$(mpc status 2>&1 | grep playing)" ]; then
            _mpd pause
        else
            _mplayer "${@}"
        fi
    elif [ -n "$(pgrep mpd)" ]; then
        _mpd "${@}"
    fi
}

progname="$(expr "${0}" : '.*/\([^/]*\)')"

if [ ! -t 0 ]; then
    #there is input comming from pipe or file, add to the end of $@
    set -- "${@}" $(cat)
fi

[ "${#}" -lt "1" ] && _die

case "$(_str2lower "${1}")" in
         pl*) _subcmd="play"     ;;
    pa*|stop) _subcmd="pause"    ;;
        pre*) _subcmd="previous" ;;
          n*) _subcmd="next"     ;;
          t*) _subcmd="toggle"   ;;
        sta*) _subcmd="status"   ;;
        pri*) _subcmd="print"
              if [ -n "${2}" ]; then
                  case "$(_str2lower "${2}")" in
                      t*) _param="title" ;;
                  esac
              fi
            ;;
   -h|--help) _usage && exit    ;;
           *) _die ;;
esac

_player_ctrl "${_subcmd}" "${_param}"
