#!/bin/sh
#description: update wcd db if available
#usage: update-cd

#add as a cronjob for your user or root
#0 23 * * * /path/update-cd

_basename()
{   #alternative basename portable version, faster! but with possible drawbacks
    [ -z "${1}" ] && return 1 || _basename_var_name="${1}"
    [ -z "${2}" ] || _basename_var_suffix="${2}"
    case "${_basename_var_name}" in
        /*|*/*) _basename_var_name="${_basename_var_name##*/}"
    esac

    if [ -n "${_basename_var_suffix}" ] && [ "${#_basename_var_name}" -gt "${#2}" ]; then
        _basename_var_name="${_basename_var_name%$_basename_var_suffix}"
    fi

    printf "%s" "${_basename_var_name}"
}

_meta_update_cd()
{
    for dir in $(find /home -maxdepth 1 -type d -path  "/*/*"); do
        user="$(_basename "${dir}")"
        if grep "${user}" /etc/passwd >/dev/null; then
            su "${user}" -c "update-cd"
        fi
    done
    exit "${$?}"
}

if [ -f "$(command -v "wcd")" ] && [ -f "$(command -v "wcd.exec")" ]; then
    [ X"${LOGNAME}" = X"root" ] && _meta_update_cd
    mkdir "${HOME}"/.wcd; wcd.exec -GN -j -xf "${HOME}"/.ban.wcd -S "${HOME}"
    [ -f "${HOME}"/.treedata.wcd ] && mv "${HOME}"/.treedata.wcd "${HOME}"/.wcd/
fi
