#!/bin/sh
#description: display a warning when the system is running out of energy
#             and suspend|hibernate the system if no action is taken
#usage: watch-battery

#it makes more sense to run it as a cron job
#cronjob (every 3 min)
#*/3 * * * * /path/to/this/script

PATH=/bin:/usr/bin:/sbin:/usr/sbin

_basename()
{
    [ -z "${1}" ] && return 1 || _basename_var_name="${1}"
    [ -z "${2}" ] || _basename_var_suffix="${2}"
    case "${_basename_var_name}" in
        /*|*/*) _basename_var_name="$(expr "${_basename_var_name}" : '.*/\([^/]*\)')" ;;
    esac

    if [ -n "${_basename_var_suffix}" ] && [ "${#_basename_var_name}" -gt "${#2}" ]; then
        if [ X"$(printf "%s" "${_basename_var_name}" | cut -c"$((${#_basename_var_name} - ${#_basename_var_suffix} + 1))"-"${#_basename_var_name}")" \
           = X"$(printf "%s" "${_basename_var_suffix}")" ]; then
            _basename_var_name="$(printf "%s" "${_basename_var_name}" | cut -c1-"$((${#_basename_var_name} - ${#_basename_var_suffix}))")"
        fi
    fi

    printf "%s\\n" "${_basename_var_name}"
}

_usage()
{
    printf "%s\\n" "Usage: $(_basename "${0}")" >&2
    printf "%s\\n" "This program should be run as a cron job, e.g.: */3 * * * * $(_basename "${0}")" >&2
    exit 1
}

_notify()
{
    [ -z "${1}" ] && return 1

    if [ X"${TERM}" = X"linux" ] || [ -z "${TERM}" ]; then
        kill -9 $(pgrep notify-osd) >/dev/null 2>&1
        if [ X"${LOGNAME}" = X"root" ]; then
            #hack to allow notifications from cronjobs
            _notify_var_pid=$(pgrep dbus-launch|head -1)
            _notify_var_user=$(grep -z USER /proc/"${_notify_var_pid}"/environ | sed 's/USER=//')
            _notify_var_dbus="$(awk \
                '/^DBUS_SESSION_BUS_ADDRESS/ {sub(/DBUS_SESSION_BUS_ADDRESS=/,""); print $0; exit}' \
                /home/"${_notify_var_user}"/.dbus/session-bus/$(dbus-uuidgen --get)-*)"
            _notify_var_display=$(grep -z DISPLAY /proc/"${_notify_var_pid}"/environ | sed 's/DISPLAY=//')

            if ! sudo -u "${_notify_var_user}" sh -c \
                "DBUS_SESSION_BUS_ADDRESS=\"${_notify_var_dbus}\" DISPLAY=\"${_notify_var_display}\" notify-send -t 1000 \"${1}\"  \"${2}\""; then
                if command -v "gxmessage" 2>/dev/null; then
                    _notify_var_font="Monaco 9"
                    gxmessage "${_notify_var_font:+-fn "$_notify_var_font"}" "${1} ${2}" "ok"
                else
                    _notify_var_font="fixed"
                    xmessage "${_notify_var_font:+-fn "$_notify_var_font"}" "${1} ${2}" "ok"
                fi
            fi
        else
            if ! DISPLAY=:0 notify-send -t 1000 "${1}"  "${2}"; then
                if command -v "gxmessage" 2>/dev/null; then
                    _notify_var_font="Monaco 9"
                    gxmessage "${_notify_var_font:+-fn "$_notify_var_font"}" "${1} ${2}" "ok"
                else
                    _notify_var_font="fixed"
                    xmessage "${_notify_var_font:+-fn "$_notify_var_font"}" "${1} ${2}" "ok"
                fi
            fi
        fi
    else
        if [ -z "${2}" ]; then
            printf "%s\\n" "${1}"
        else
            printf "%s: %s\\n" "${1}" "${2}"
        fi
    fi
}

_valid_batt_values()
{
    if [ -z "${1}" ]; then
        return 1
    else
        _vbv_var_result="$(printf "%s" "${1}" | awk '{ gsub(/^[ \t]+|[ \t]+$/, ""); print }')"
        while [ "${_vbv_var_result}" ]; do
            _vbv_var_option="${_vbv_var_result%%,*}"
            if ! printf "%s" "${_vbv_var_option}" | grep -v "[^0-9]" >/dev/null; then
                return 1
            fi
            [ X"${_vbv_var_result}" = X"${_vbv_var_option}" ] && _vbv_var_result='' \
                || _vbv_var_result="${_vbv_var_result#*,}"
        done
        printf "%s" "${1}"
    fi
}

_sort_batt_values()
{ if [ -z "${1}" ]; then
        return 1
    else
        _sbv_var_result="$(printf "%s" "${1}" | awk '{ gsub(/^[ \t]+|[ \t]+$/, ""); print }')"
        _sbv_var_result="$(printf "%s" "${_sbv_var_result}" | tr "," "\n" | sort -n |tr "\n" ",")"
        printf "%s" "${_sbv_var_result%,}"
    fi
}

for arg in "${@}"; do #parse options
    case "${arg}" in
        --) shift; break  ;;
        -h|--help) _usage ;;
        -*) printf "%s\\n" "$(expr "${0}" : '.*/\([^/]*\)'): unrecognized option \`${arg}'" >&2; _usage ;;
    esac
done

progname="$(_basename "${0}")"
exec 9>/tmp/"${progname}".lock
[ X"${LOGNAME}" = X"root" ] && chmod 666 /tmp/"${progname}".lock
if ! flock -n 9 ; then
    _notify "${progname}: another instance is running";
    exit 1
fi

if [ ! -f "$(command -v notify-send)" ] || [ ! -f "$(command -v pm-hibernate)" ] || [ ! -f "$(command -v acpi)" ]; then
    _notify  "Error" "you need to install acpi, notify-send and pm-utils to run this program"
    exit 1
fi

#=====VARS=====
#current battery status (Charging/Discharging/AC/Unknown)
stat="$(acpi -b | awk '{sub(",", ""); print $3}')"
#battery percentage
batt_current="$(acpi -b |awk '{if ($0 ~ "%,") sub("%,", ""); else sub("%", ""); print $4}')"
batt_last_seen="$(cat /tmp/"${progname}" 2>/dev/null)"
[ X"${LOGNAME}" = X"root" ] && user=$(grep 1000 /etc/group | cut -d: -f1) || user="${LOGNAME}"
action="$(HOME=/home/$user minos-config watch-battery-action 2>/dev/null)"
[ -z "${action}" ] && action="$(command -v pm-hibernate)"
batt_values="$(HOME=/home/$user minos-config watch-battery-values 2>/dev/null)"
[ -z "$(_valid_batt_values "${batt_values}")" ] && batt_values="15,10,7,5"
batt_values="$(_sort_batt_values "${batt_values}")"
#=============

if command -v "gksudo" >/dev/null 2>&1; then
    _sudo="gksudo"
else
    _sudo="sudo"
fi

# If Discharging...
if [ X"${stat}" = X"Discharging" ]; then
    batt_values_buf="${batt_values}"; i="0"
    while [ "${batt_values_buf}" ]; do
        batt_value="${batt_values_buf%%,*}"; i="$((${i}+1))"
        if [ "${batt_current}" -lt "${batt_value}" ]; then
            case "${i}" in
                1)  # Battery in the latest valid value -> force to take action
                    _notify "Critical" "battery under ${batt_value}%, the system will hibernate in 30 seconds, unless you plugin the computer"
                    j=0 ; while [ "${j}" -lt "30" ]; do
                        sleep 1
                        stat="$(acpi -b | awk '{sub(",", ""); print $3}')"
                        if [ X"${stat}" != X"Discharging" ]; then
                            _notify  "Charging" "charging now..."
                            break
                        fi
                        j="$((${j} + 1))"
                    done

                    #check for the last time if someone has pluged in the machine
                    stat="$(acpi -b | awk '{sub(",", ""); print $3}')"

                    if [ X"${stat}" = X"Discharging" ]; then
                        [ -x "$(command -v mpc)" ] && mpc stop
                        if [ X"${LOGNAME}" = X"root" ]; then
                            HOME=/home/$user USER=$user DISPLAY=:0 ${action}
                        else
                            ${_sudo} ${action}
                        fi
                    fi
                    ;;
                *)
                    [ X"${batt_last_seen}" = X"${batt_value}" ] && exit 0
                    _notify  "Warning" "battery under ${batt_value}%"
                    batt_last_seen="${batt_value}"
                    ;;
            esac
            printf "%s\\n" "${batt_last_seen}" > /tmp/"${progname}"
            [ X"${LOGNAME}" = X"root" ] && chmod 666 /tmp/"${progname}" || :
            break
        fi
        [ X"${batt_values_buf}" = X"${batt_value}" ] && batt_values_buf='' || batt_values_buf="${batt_values_buf#*,}"
    done
fi
