#!/bin/sh
#description: display a warning when the system is running out of energy
#             suspend|hibernate if no manual action is taken
#usage: watch-battery

#it indend to be used as a cron job
#eg, (every 3 min)
#*/3 * * * * /path/to/this/script

PROGNAME="$(basename "${0}")"

PATH=/bin:/usr/bin:/sbin:/usr/sbin

_usage() {
    printf "%s\\n" "Usage: ${PROGNAME}"
    printf "%s\\n" "This program should be run as a cron job, eg.: */1 * * * * ${PROGNAME}"
}

_die() {
    [ -z "${1}" ] || printf "%s\\n" "${*}" >&2
    _usage >&2; exit 1
}

_notify() {
    [ -z "${1}" ] && return 1

    #set -x
    #exec > /tmp/watch-battery.debug 2>&1
    if [ X"${TERM}" = X"linux" ] || [ -z "${TERM}" ]; then
        kill -9 $(pgrep notify-osd) >/dev/null 2>&1
        if [ X"${LOGNAME}" = X"root" ]; then
            #hack to allow notifications from cronjobs
            _notify__pid=$(pgrep dbus-launch|head -1)
            _notify__user=$(grep -z USER /proc/"${_notify__pid}"/environ | sed 's/USER=//')
            _notify__dbus="$(awk \
                '/^DBUS_SESSION_BUS_ADDRESS/ {sub(/DBUS_SESSION_BUS_ADDRESS=/,""); print $0; exit}' /home/"${_notify__user}"/.dbus/session-bus/$(dbus-uuidgen --get)-*)"
            _notify__display=$(grep -z DISPLAY /proc/"${_notify__pid}"/environ | sed 's/DISPLAY=//')

            #fucking hate dbus/notify-send
            su "${_notify__user}" -c "sh -c 'DISPLAY=\"${_notify__display}\" notify-send -t 1000 \"${1}\"  \"${2}\"'"
            su "${_notify__user}" -c "sh -c 'DBUS_SESSION_BUS_ADDRESS=\"${_notify__dbus}\" DISPLAY=\"${_notify__display}\" notify-send -t 1000 \"${1}\"  \"${2}\"'"
            #if ! su "${_notify__user}" -c "sh -c 'DBUS_SESSION_BUS_ADDRESS=\"${_notify__dbus}\" DISPLAY=\"${_notify__display}\" notify-send -t 1000 \"${1}\"  \"${2}\"'"; then
            #if ! su "${_notify__user}" -c "sh -c 'DISPLAY=\"${_notify__display}\" notify-send -t 1000 \"${1}\"  \"${2}\"'"; then
            #if ! notify-send -t 1000 "${1}"  "${2}"; then
            if [ ! "${?}" = "0" ]; then
                if command -v "gxmessage" 2>/dev/null; then
                    _notify__font="Monaco 9"
                    DISPLAY="${_notify__display}" gxmessage "${_notify__font:+-fn "$_notify__font"}" "${1} ${2}" "ok"
                else
                    _notify__font="fixed"
                    DISPLAY="${_notify__display}" xmessage "${_notify__font:+-fn "$_notify__font"}" "${1} ${2}" "ok"
                fi
            fi
        else
            if ! DISPLAY=:0 notify-send -t 1000 "${1}"  "${2}"; then
                if command -v "gxmessage" 2>/dev/null; then
                    _notify__font="Monaco 9"
                    DISPLAY=:0 gxmessage "${_notify__font:+-fn "$_notify__font"}" "${1} ${2}" "ok"
                else
                    _notify__font="fixed"
                    DISPLAY=:0 xmessage "${_notify__font:+-fn "$_notify__font"}" "${1} ${2}" "ok"
                fi
            fi
        fi
    else
        if [ -z "${2}" ]; then
            printf "%s\\n" "${1}"
        else
            printf "%s: %s\\n" "${1}" "${2}"
        fi
    fi
}

_valid_batt_values() {
    if [ -z "${1}" ]; then
        return 1
    else
        _vbv__result="$(printf "%s\\n" "${1}" | awk '{ gsub(/^[ \t]+|[ \t]+$/, ""); print $1}')"
        while [ "${_vbv__result}" ]; do
            _vbv__option="${_vbv__result%%,*}"
            if ! printf "%s\\n" "${_vbv__option}" | grep -v "[^0-9]" >/dev/null; then
                return 1
            fi
            [ X"${_vbv__result}" = X"${_vbv__option}" ] && _vbv__result='' \
                || _vbv__result="${_vbv__result#*,}"
        done
        printf "%s\\n" "${1}"
    fi
}

_sort_batt_values() {
    if [ -z "${1}" ]; then
        return 1
    else
        _sbv__result="$(printf "%s\\n" "${1}" | awk '{ gsub(/^[ \t]+|[ \t]+$/, ""); print $1}')"
        _sbv__result="$(printf "%s\\n" "${_sbv__result}" | tr "," "\n" | sort -n |tr "\n" ",")"
        printf "%s\\n" "${_sbv__result%,}"
    fi
}

for arg in "${@}"; do #parse options
    case "${arg}" in
        --) shift; break ;;
        -h|--help) _usage && exit ;;
        -*) _die "${PROGNAME}: unrecognized option '${arg}'" ;;
    esac
done

[ X"${LOGNAME}" = X"root" ] && user="$(grep 1000 /etc/group | cut -d: -f1)" || user="${LOGNAME}"
bin="$(HOME=/home/"${user}" minos-config battery 2>/dev/null | awk '{print $1}')"
case "${bin}" in
      no|NO|No|nO|false|disabled) exit ;;
    watch-battery) :             ;;
                *) exec "${bin}" ;;
esac

exec 9>/tmp/"${PROGNAME}".lock
[ X"${LOGNAME}" = X"root" ] && chmod 666 /tmp/"${PROGNAME}".lock
if ! flock -n 9 ; then
    _notify "${PROGNAME}: another instance is running";
    exit 1
fi

if [ ! -f "$(command -v notify-send)" ] || [ ! -f "$(command -v pm-hibernate)" ] || [ ! -f "$(command -v acpi)" ]; then
    _notify  "Error" "install 'acpi', 'notify-send' and 'pm-utils' to run this program"
    exit 1
fi

#=====VARS=====
#current battery status (Charging/Discharging/AC/Unknown)
stat="$(acpi -b | awk '{sub(",", ""); print $3}')"
#battery percentage
batt_current="$(acpi -b |awk '{if ($0 ~ "%,") sub("%,", ""); else sub("%", ""); print $4}')"
batt_last_seen="$(cat /tmp/"${PROGNAME}" 2>/dev/null)"
batt_at="$(HOME=/home/"${user}" minos-config battery-alerts 2>/dev/null)"
[ -z "$(_valid_batt_values "${batt_at}")" ] && batt_at="$(HOME=/home/"${user}" minos-config battery-alerts 2>/dev/null)"
[ -z "$(_valid_batt_values "${batt_at}")" ] && batt_at="15,10,7,5"
batt_at="$(_sort_batt_values "${batt_at}")"

action="$(HOME=/home/"${user}" minos-config battery-action 2>/dev/null)"
if [ -z "${action}" ]; then
    if command -v "dmenu-session" >/dev/null 2>&1; then
        action="$(command -v "dmenu-session") hibernate"
    else
        action="$(HOME=/home/"${user}" minos-config hibernate 3>/dev/null)"
        [ -z "${action}" ] && action="$(command -v pm-hibernate)"
    fi
fi

case "${action}" in
    dmenu-session*) _sudo="" ;;
    *)  if command -v "gksudo" >/dev/null 2>&1; then
            _sudo="gksudo"
        else
            _sudo="sudo"
        fi
        ;;
esac
#=============

if [ X"${stat}" = X"Discharging" ]; then
    batt_values_buf="${batt_at}"; i="0"
    while [ "${batt_values_buf}" ]; do
        batt_value="${batt_values_buf%%,*}"; i="$((${i}+1))"
        if [ "${batt_current}" -lt "${batt_value}" ]; then
            case "${i}" in
                1)  # Battery in the latest valid value -> force to take action
                    _notify "Critical" "battery under ${batt_value}%, the system will hibernate in 30 seconds, unless you plugin the computer"
                    j=0 ; while [ "${j}" -lt "30" ]; do
                        sleep 1
                        stat="$(acpi -b | awk '{sub(",", ""); print $3}')"
                        if [ X"${stat}" != X"Discharging" ]; then
                            _notify  "Charging" "charging now..."
                            break
                        fi
                        j="$((${j} + 1))"
                    done

                    #check for the last time if someone has pluged in the machine
                    stat="$(acpi -b | awk '{sub(",", ""); print $3}')"

                    if [ X"${stat}" = X"Discharging" ]; then
                        [ -x "$(command -v mpc)" ] && mpc stop
                        if [ X"${LOGNAME}" = X"root" ]; then
                            HOME=/home/$user USER=$user DISPLAY=:0 ${action}
                        else
                            ${_sudo} ${action}
                        fi
                    fi
                    ;;
                *)
                    [ X"${batt_last_seen}" = X"${batt_value}" ] && exit 0
                    _notify  "Warning" "battery under ${batt_value}%"
                    batt_last_seen="${batt_value}"
                    ;;
            esac
            printf "%s\\n" "${batt_last_seen}" > /tmp/"${PROGNAME}"
            [ X"${LOGNAME}" = X"root" ] && chmod 666 /tmp/"${PROGNAME}" || :
            break
        fi
        [ X"${batt_values_buf}" = X"${batt_value}" ] && batt_values_buf='' || batt_values_buf="${batt_values_buf#*,}"
    done
fi
